//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Traceability.brnet_sendEmail {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SendMessageSoap", Namespace="http://tempuri.org/")]
    public partial class SendMessage : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmail_v1OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmail_v2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SendMessage() {
            this.Url = global::Traceability.Properties.Settings.Default.WM_Traceability21_brnet_sendEmail_SendMessage;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendEmailCompletedEventHandler SendEmailCompleted;
        
        /// <remarks/>
        public event SendEmail_v1CompletedEventHandler SendEmail_v1Completed;
        
        /// <remarks/>
        public event SendSmsCompletedEventHandler SendSmsCompleted;
        
        /// <remarks/>
        public event SendEmail_v2CompletedEventHandler SendEmail_v2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendEmail(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile) {
            object[] results = this.Invoke("SendEmail", new object[] {
                        from,
                        DisplayName,
                        to,
                        subject,
                        MessageText,
                        cc,
                        bcc,
                        AttachFile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailAsync(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile) {
            this.SendEmailAsync(from, DisplayName, to, subject, MessageText, cc, bcc, AttachFile, null);
        }
        
        /// <remarks/>
        public void SendEmailAsync(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, object userState) {
            if ((this.SendEmailOperationCompleted == null)) {
                this.SendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailOperationCompleted);
            }
            this.InvokeAsync("SendEmail", new object[] {
                        from,
                        DisplayName,
                        to,
                        subject,
                        MessageText,
                        cc,
                        bcc,
                        AttachFile}, this.SendEmailOperationCompleted, userState);
        }
        
        private void OnSendEmailOperationCompleted(object arg) {
            if ((this.SendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailCompleted(this, new SendEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_v1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendEmail_v1(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName) {
            object[] results = this.Invoke("SendEmail_v1", new object[] {
                        from,
                        DisplayName,
                        to,
                        subject,
                        MessageText,
                        cc,
                        bcc,
                        AttachFile,
                        prmMailPriority,
                        AppName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmail_v1Async(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName) {
            this.SendEmail_v1Async(from, DisplayName, to, subject, MessageText, cc, bcc, AttachFile, prmMailPriority, AppName, null);
        }
        
        /// <remarks/>
        public void SendEmail_v1Async(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName, object userState) {
            if ((this.SendEmail_v1OperationCompleted == null)) {
                this.SendEmail_v1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmail_v1OperationCompleted);
            }
            this.InvokeAsync("SendEmail_v1", new object[] {
                        from,
                        DisplayName,
                        to,
                        subject,
                        MessageText,
                        cc,
                        bcc,
                        AttachFile,
                        prmMailPriority,
                        AppName}, this.SendEmail_v1OperationCompleted, userState);
        }
        
        private void OnSendEmail_v1OperationCompleted(object arg) {
            if ((this.SendEmail_v1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmail_v1Completed(this, new SendEmail_v1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSms(string from, string to, string subject, string MessageText) {
            object[] results = this.Invoke("SendSms", new object[] {
                        from,
                        to,
                        subject,
                        MessageText});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsAsync(string from, string to, string subject, string MessageText) {
            this.SendSmsAsync(from, to, subject, MessageText, null);
        }
        
        /// <remarks/>
        public void SendSmsAsync(string from, string to, string subject, string MessageText, object userState) {
            if ((this.SendSmsOperationCompleted == null)) {
                this.SendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsOperationCompleted);
            }
            this.InvokeAsync("SendSms", new object[] {
                        from,
                        to,
                        subject,
                        MessageText}, this.SendSmsOperationCompleted, userState);
        }
        
        private void OnSendSmsOperationCompleted(object arg) {
            if ((this.SendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsCompleted(this, new SendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail_v2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendEmail_v2(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName) {
            object[] results = this.Invoke("SendEmail_v2", new object[] {
                        from,
                        DisplayName,
                        to,
                        subject,
                        MessageText,
                        cc,
                        bcc,
                        AttachFile,
                        prmMailPriority,
                        AppName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmail_v2Async(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName) {
            this.SendEmail_v2Async(from, DisplayName, to, subject, MessageText, cc, bcc, AttachFile, prmMailPriority, AppName, null);
        }
        
        /// <remarks/>
        public void SendEmail_v2Async(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName, object userState) {
            if ((this.SendEmail_v2OperationCompleted == null)) {
                this.SendEmail_v2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmail_v2OperationCompleted);
            }
            this.InvokeAsync("SendEmail_v2", new object[] {
                        from,
                        DisplayName,
                        to,
                        subject,
                        MessageText,
                        cc,
                        bcc,
                        AttachFile,
                        prmMailPriority,
                        AppName}, this.SendEmail_v2OperationCompleted, userState);
        }
        
        private void OnSendEmail_v2OperationCompleted(object arg) {
            if ((this.SendEmail_v2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmail_v2Completed(this, new SendEmail_v2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendEmailCompletedEventHandler(object sender, SendEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendEmail_v1CompletedEventHandler(object sender, SendEmail_v1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmail_v1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmail_v1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendSmsCompletedEventHandler(object sender, SendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendEmail_v2CompletedEventHandler(object sender, SendEmail_v2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmail_v2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmail_v2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591